### ISSUE TITLE
Windows - non EN-US systems, backtick encoding

### ISSUE THREAD

**Issue by MSP-Greg** [MSP-Greg/psych#1]
@tan-wei

If you have a minute, wondering what the encoding of Ruby backtick commands is.  I assume both are the same (?).

```
ruby -e "puts `sh --version`.encoding"
ruby -e "puts `ver`.encoding"
```

**Comment by tan-wei** [comment]
Yes, they are the same:
```console
C:\Cmder
λ ruby -e "puts `sh --version`.encoding"
UTF-8

C:\Cmder
λ ruby -e "puts `ver`.encoding"
UTF-8
```

**Comment by MSP-Greg** [comment]
I'm not sure if this is an issue with 'Cmder' or not. From a normal Windows cmd window, the above commands match my  `Encoding.default_external` encoding, which is IBM437...

**Comment by tan-wei** [comment]
I'v tried in `cmd` instead of `Cmder`. Just the same.

**Comment by MSP-Greg** [comment]
What is `Encoding.default_external` on your system?

If it's not `UTF-8`, maybe try:
```
ruby -e "puts `ver`.encode(Encoding.default_external, 'UTF-8')"
```

Thanks for helping with this.  This seems like a Ruby bug, and there's 25 days before 2.7 is released...

**Comment by tan-wei** [comment]
Sorry for the delay.

It prints:
```console
C:\cmder
λ ruby -e "puts `ver`.encode(Encoding.default_external, 'UTF-8')"

Microsoft Windows [�汾 10.0.18362.476]
```

**Comment by tan-wei** [comment]
Actully, in pry:
```console
[1] pry(main)> `ver`
=> "\nMicrosoft Windows [\xB0汾 10.0.18362.476]\n"
```
Strange string with "\xB0汾", and I can tell you that "汾" here is obviously a meaningless word (its real meaning is a name of a river)

**Comment by MSP-Greg** [comment]
Thanks. What is:
```
ruby -e "puts Encoding.default_external"
```

If you could maybe check both cmder & cmd...

**Comment by tan-wei** [comment]
Cmder:
```console
C:\cmder
λ ruby -e "puts Encoding.default_external"
UTF-8
```

cmd:
```console
Microsoft Windows [版本 10.0.18362.476]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\Winterreise>ruby -e "puts Encoding.default_external"
UTF-8
```
Here, "版本" means "version".

**Comment by MSP-Greg** [comment]
Thanks.  Sorry for the trouble, but I can't repo this, so please pardon all the questions...

Seems odd.  On my system, both
```
ruby -e "puts Encoding.find 'locale'"
```
and
```
ruby -e "puts Encoding.default_external"
```

show IBM437.

I assume `ruby -e "puts Encoding.find 'locale'"` is also UTF-8?  Is RUBYOPT set in the ENV?

**Comment by tan-wei** [comment]
Sorry, I didn't know RUBYOPT was set in ENV: `RUBYOPT=-Eutf-8", so:
```console
C:\Users\Winterreise>ruby -e "puts Encoding.find 'locale'"
GBK

C:\Users\Winterreise>ruby -e "puts Encoding.default_external"
UTF-8
```
It could not be set myself. Maybe it's RubyInstaller's action.

**Comment by MSP-Greg** [comment]
No problem.  I don't think I've ever used the RubyInstaller exe.  It may be a 'default' option.

Anyway, first things first, does `ridk version` work (you may have already checked)?

If not, how about the output from:
```
ruby -e "puts `ver`.encode(Encoding.find('locale'), 'UTF-8')"
```

**Comment by tan-wei** [comment]
I've changed nothing for now. It's the same with `cmd`:
```console
C:\Users\Winterreise>ruby -e "puts `ver`.encode(Encoding.find('locale'), 'UTF-8')"
Traceback (most recent call last):
        1: from -e:1:in `<main>'
-e:1:in `encode': "\xB0" on UTF-8 (Encoding::InvalidByteSequenceError)

C:\Users\Winterreise>ridk version
Traceback (most recent call last):
        11: from C:/Ruby26/bin/ridk.cmd:39:in `<main>'
        10: from C:/Ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:24:in `run!'
         9: from C:/Ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:168:in `print_version'
         8: from C:/Ruby26/lib/ruby/2.6.0/psych/core_ext.rb:13:in `to_yaml'
         7: from C:/Ruby26/lib/ruby/2.6.0/psych.rb:513:in `dump'
         6: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:118:in `push'
         5: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
         4: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
         3: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `each'
         2: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
         1: from C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
C:/Ruby26/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:298:in `visit_String': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by tan-wei** [comment]
I think the problem is the byte `\xB0`. So what does the result of `ver` come from?

**Comment by MSP-Greg** [comment]
Yes, that is the issue.  `ver` is just a Windows command that shows OS version.

>> I've changed nothing for now

Sorry I wasn't clear.  I meant for the commands to be run with `RUBYOPT` cleared.  Is that what you replied with?  `RUBYOPTS` is telling Ruby that external data is UTF-8, but it's not.  If we clear `RUBYOPT`, then we'll see if Ruby can encoding the string correctly.  I think...

**Comment by tan-wei** [comment]
After I clear `RUBYOPT`, now it works:
```console
C:\Cmder
λ set RUBYOPT=

C:\Cmder
λ ridk version
---
ruby:
  path: C:/Ruby26
  version: 2.6.5
  platform: i386-mingw32
ruby_installer:
  package_version: 2.6.5-1
  git_commit: d3e0c65
msys2:
  path: C:\Ruby26\msys32
cc: i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 9.2.0
os: Microsoft Windows [版本 10.0.18362.476]
```

**Comment by MSP-Greg** [comment]
Good.

A few years ago, Ruby wasn't fully tested on Windows.  It now is.

Thanks for being patient, since I work with a Windows encoding that is UTF-8 compatible, encoding issues aren't something I've worked with much...

**Comment by tan-wei** [comment]
You're welcome. It's my pleasure to help Ruby dev, because Ruby is one of my favorite.
